version: "3.8"
services:
  bskybot:
    build: .
    restart: unless-stopped
    volumes:
      - ./sessionData:/sessionData
    env_file:
      - .env
    environment:
      - NAME=Aaron
      - USER_DID=did:plc:ksjfbda7262bbqmuoly54lww
      #- TRACKER_BSKY_HANDLE=
      #- TRACKER_BSKY_PASSWORD=
      #- DEBUG_LOG_ACTIVE=true
      #- DEBUG_LOG_LEVEL=info
      #- JETSTREAM_URL='wss://jestream1.us-west.bsky.network/subscribe'
      #- SESSION_DATA_PATH='/sessionData'
    networks:
      - bun
networks:
  bun:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
