version: "3.8"
services:
  bskybot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NAME=TEST
      - USER_DID=did:plc:example
      #- TRACKER_BSKY_HANDLE=
      #- TRACKER_BSKY_PASSWORD=
      #- DEBUG_LOG_ACTIVE=true
      #- DEBUG_LOG_LEVEL=info
      #- JETSTREAM_URL='wss://jestream1.us-west.bsky.network/subscribe'
      #- SESSION_DATA_PATH='/sessionData'
    networks_mode: bridge
