version: "3.8"
services:
  bskybot:
    depends_on:
      - jetstream
    build: .
    restart: unless-stopped
    volumes:
      - ./sessionData:/sessionData
    env_file:
      - .env
    environment:
      - NAME=TEST
      - USER_DID=did:plc:example
      #- TRACKER_BSKY_HANDLE=
      #- TRACKER_BSKY_PASSWORD=
      #- DEBUG_LOG_ACTIVE=true
      #- DEBUG_LOG_LEVEL=info
      #- JETSTREAM_URL='ws://jetstream:6008/subscribe'
      #- SESSION_DATA_PATH='/sessionData'
    networks:
      - bun


  jetstream:
    image: "ghcr.io/bluesky-social/jetstream:sha-ea96859b93d1790ff20bb168e5fc442d462cea1e" 
    container_name: jetstream
    restart: unless-stopped
    environment:
      - CURSOR_FILE=/data/cursor.json
    ports:
      - "6008:6008"
    volumes:
      - ./data:/data
    networks:
      - bun

networks:
  bun:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
